model:
  name: VariationalAutoencoder
  input_dim: 500              # Number of input features (e.g., 500 samples from ECG/PCG)
  latent_dim: 32              # Dimensionality of latent space
  hidden_dims: [128, 64]      # Encoder/Decoder hidden layers
  activation_fn: relu         # relu, leaky_relu, etc.
  output_dim: 500             # Same as input_dim (for reconstruction)

training:
  batch_size: 64              # Mini-batch size
  epochs: 100                 # Number of epochs to train
  learning_rate: 0.001        # Initial learning rate
  beta: 1.0                   # KL-divergence weight (for Î²-VAE)
  optimizer: adam             # Optimizer type

loss:
  reconstruction_loss: mse    # Could be mse, bce
  kl_divergence_weight: ${training.beta}  # Reference to beta

hardware:
  use_gpu: true               # Set false to run on CPU
  num_workers: 4              # Data loader workers

logging:
  log_interval: 10            # Log metrics every n batches
  save_model: true            # Save model after training
  model_save_path: "./models/vae.pt"
  log_dir: "./logs"

seed:
  random_seed: 42             # For reproducibility
